### PR TITLE
Remove an unnecessary use of unwrap_unchecked

### PR DESCRIPTION
**Pull request by steffahn**

### CODE REVIEW

**Comment by steffahn** [comment]
Squashed 3 commits to one.

By the way, if you merge this, you can avoid the merge commit by choosing “Rebase and Merge”

**Comment by steffahn** [comment]
_(renamed variable in `Ok(x) => x` to `Ok(array) => array`)_

**Comment by c410-f3r** [comment]
The compiler ability of removing one match arm because of `Infallible` is something new to me. Thanks

**Comment by steffahn** [comment]
The ability to remove a match arm like this is new to me, too. I first wrote 
```
Ok(array) => array,
Err(infallible) => match infallible {},
```
which is the old way of achieving the same thing, but the compiler warning about an unreachable match arm came in, suggesting to remove the second arm entirely.

**Pull request merged**
